---
  - name: Initializing Kubernetes cluster
    shell: kubeadm init --ignore-preflight-errors=true --pod-network-cidr={{cidr_v}}
    register: output

  - name: Copying required files
    shell: |
     mkdir -p $HOME/.kube
     sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
     sudo chown $(id -u):$(id -g) $HOME/.kube/config

  - name: Install Network Add-on 
    command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

  - name: get join command
    shell: kubeadm token create --print-join-command
    register: join_command_raw

  - name: debug join command
    debug:
      msg: "{{ join_command_raw.stdout_lines[0] }}"

  - name: Register workers host with jooin command variable
    add_host:
      name: dummy
      join_command: "{{ join_command_raw.stdout_lines[0] }}"
