ad_addr: 10.11.12.2
$cidr_v: 10.244.0.0/16
cidr_v: 196.168.0.0/16

packages:
- firewalld
- lvm2
- yum-utils
- device-mapper-persistent-data
- docker-ce-19.03.8
- docker-ce-cli-19.03.8
- containerd.io-1.2.13
- kubelet-1.20.1-0
- kubeadm-1.20.1-0
- kubectl-1.20.1-0

services:
- firewalld
- kubelet
- docker

token_file: join_token
